# Generated by Django 2.2.10 on 2020-09-22 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autologin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
