# Generated by Django 2.2.10 on 2020-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless_login', '0002_autologin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='autologin',
            name='link_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
